USE herochallenge;

INSERT INTO hero (id, name, class, story, weapon) VALUES (uuid(), 'Joy Doe', 'Warrior', 'Simple Warrior', 1);
INSERT INTO hero (id, name, class, story, weapon) VALUES (uuid(), 'Max Doe', 'Archer', 'Simple Archer', 2);
INSERT INTO hero (id, name, class, story, weapon) VALUES (uuid(), 'Jo Doe', 'Warrior', 'Base Warrior', 1);
INSERT INTO hero (id, name, class, story, weapon) VALUES (uuid(), 'Ma Doe', 'Archer', 'Base Archer', 2);
