USE herochallenge;

INSERT INTO hero (id, name, class, story, weapon) VALUES (1, 'Joy Doe', 'Warrior', 'Simple Warrior', 'Sword');
INSERT INTO hero (id, name, class, story, weapon) VALUES (2, 'Max Doe', 'Archer', 'Simple Archer', 'Bow');
INSERT INTO hero (id, name, class, story, weapon) VALUES (3, 'Jo Doe', 'Warrior', 'Base Warrior', 'Sword');
INSERT INTO hero (id, name, class, story, weapon) VALUES (4, 'Ma Doe', 'Archer', 'Base Archer', 'Bow');
